// <auto-generated />
namespace NationalUnion.Domain.Repository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DatasummaryAddAvalibleColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DatasummaryAddAvalibleColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201407250413133_DatasummaryAddAvalibleColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
